"""
Django settings for prj_mng1 project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6no@d*tvla8fae-@k3uiagmv&)$5cg@@qessce2n8tc3#^3)wt'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django_extensions',
    'debug_toolbar',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # custom Apps
    'userauths',
    'user_dashboard',
    'addon',
    'hostel',
    
    # third party apps
    'import_export',
    'crispy_forms',
    'mathfilters',
    'ckeditor_uploader',
    'django_ckeditor_5',
    'taggit',



]

MIDDLEWARE = [
    'django.contrib.sessions.middleware.SessionMiddleware',
    
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'prj_mng1.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'prj_mng1.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'hostel',
        'PASSWORD' : 't@n!$h@184',
        'USER' : 'root',
        'HOST':'localhost',
    }
}



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR,'media')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL ="userauths.User"

JAZZMIN_SETTINGS = {
    "site_title": "Desphixs",
    "site_header": "Desphixs",
    "site_brand": "Welcome to hosttellers",
    "site_icon": "assets/logo/favicon.png",
    #"site_logo": "assets/logo/favicon.png",
    "welcome_sign": "Welcome To Tanisha",
    "copyright": "Tanisha",
    "user_avatar": "images/photos/logo.jpg",
    "topmenu_links": [
        {"name": "Dashboard", "url": "home", "permissions": ["auth.view_user"]},
        {"model": "auth.User"},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "order_with_respect_to": [
        "add_model_name_here"
    ],
    "icons": {
        "admin.LogEntry": "fas fa-file",
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "userauths.User": "fas fa-user",
        "userauths.Profile":"fas fa-address-card",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-arrow-circle-right",
    "related_modal_active": False,
    
    "custom_js": None,
    "show_ui_builder": True,
    
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
    },
}

# Jazzmin UI Tweaks
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": True,
    "brand_small_text": False,
    "brand_colour": "navbar-indigo",
    "accent": "accent-olive",
    "navbar": "navbar-indigo navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-indigo",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}

# customColorPalette = [
#   { color: "hsl(4, 90%, 58%)", label: "Red" },
#   { color: "hsl(340, 82%, 52%)", label: "Pink" },
#   { color: "hsl(291, 64%, 42%)", label: "Purple" },
#   { color: "hsl(262, 52%, 47%)", label: "Deep Purple" },
#   { color: "hsl(231, 48%, 48%)", label: "Indigo" },
#   { color: "hsl(207, 90%, 54%)", label: "Blue" }
# ];

# CKEDITOR_5_CONFIGS = {
#   default: {
#     toolbar: [
#       "heading",
#       "bold",
#       "italic",
#       "link",
#       "bulletedList",
#       "numberedList",
#       "blockQuote",
#       "imageUpload"
#     ],
#     language: {
#       ui: "en",
#       content: "en"
#     },
#     blockToolbar: [
#       "paragraph",
#       "heading1",
#       "heading2",
#       "heading3",
#       "bulletedList",
#       "numberedList",
#       "blockQuote"
#     ],
#     heading: {
#       options: [
#         { model: "paragraph", title: "Paragraph", class: "ck-heading_paragraph" },
#         { model: "heading1", view: "h1", title: "Heading 1", class: "ck-heading_heading1" },
#         { model: "heading2", view: "h2", title: "Heading 2", class: "ck-heading_heading2" },
#         { model: "heading3", view: "h3", title: "Heading 3", class: "ck-heading_heading3" }
#       ]
#     },
#     list: {
#       properties: {
#         styles: true,
#         startIndex: true,
#         reversed: true
#       }
#     },
#     htmlSupport: {
#       allow: [
#         {
#           name: /^.*$/,
#           attributes: true,
#           classes: true,
#           styles: true
#         }
#       ]
#     },
#     image: {
#       toolbar: [
#         "imageTextAlternative",
#         "|",
#         "imageStyle:alignLeft",
#         "imageStyle:alignCenter",
#         "imageStyle:alignRight",
#         "imageStyle:side"
#       ],
#       styles: [
#         "full",
#         "side",
#         "alignLeft",
#         "alignCenter",
#         "alignRight"
#       ]
#     },
#     table: {
#       contentToolbar: [
#         "tableColumn",
#         "tableRow",
#         "mergeTableCells",
#         "tableProperties",
#         "tableCellProperties"
#       ],
#       tableProperties: {
#         borderColors: customColorPalette,
#         backgroundColors: customColorPalette
#       },
#       tableCellProperties: {
#         borderColors: customColorPalette,
#         backgroundColors: customColorPalette
#       }
#     }
#   }
# };
# settings.py
SESSION_COOKIE_AGE = 1209600  # 2 weeks
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
