# Generated by Django 4.2.16 on 2024-09-19 05:11

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('hostel', '0002_booking_alter_hostel_description_staffonduty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='tags',
        ),
        migrations.AddField(
            model_name='hostel',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
